
package com.epam.labTA.web.soap;

import io.qameta.allure.Step;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://soap.service.labTA.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService extends com.epam.labTA.web.CalculatorService{

    
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPercentage", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetPercentage")
    @ResponseWrapper(localName = "getPercentageResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetPercentageResponse")
    public double getPercentage(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException
    ;

  
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultiply", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetMultiply")
    @ResponseWrapper(localName = "getMultiplyResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetMultiplyResponse")
    public double getMultiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException
    ;

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalculate", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetCalculate")
    @ResponseWrapper(localName = "getCalculateResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetCalculateResponse")
    public double getCalculate(
        @WebParam(name = "arg0", targetNamespace = "")
        Calculator arg0)
        throws SoapException
    ;

   
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDivide", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetDivide")
    @ResponseWrapper(localName = "getDivideResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetDivideResponse")
    public double getDivide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException
    ;

    
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubtract", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetSubtract")
    @ResponseWrapper(localName = "getSubtractResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetSubtractResponse")
    public double getSubtract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException
    ;

    
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdd", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetAdd")
    @ResponseWrapper(localName = "getAddResponse", targetNamespace = "http://soap.service.labTA.com/", className = "soap.GetAddResponse")
    public double getAdd(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException
    ;

}
