
package com.epam.labTA.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorServiceImpService", targetNamespace = "http://soap.service.labTA.com/", wsdlLocation = "http://localhost:8080/OlenkaSaloCalculatorService/calculatorSoap?wsdl")
public class CalculatorServiceImpService
    extends Service
{

    private final static URL CALCULATORSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORSERVICEIMPSERVICE_EXCEPTION;
    private final static QName CALCULATORSERVICEIMPSERVICE_QNAME = new QName("http://soap.service.labTA.com/", "CalculatorServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OlenkaSaloCalculatorService/calculatorSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSERVICEIMPSERVICE_WSDL_LOCATION = url;
        CALCULATORSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public CalculatorServiceImpService() {
        super(__getWsdlLocation(), CALCULATORSERVICEIMPSERVICE_QNAME);
    }

    public CalculatorServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSERVICEIMPSERVICE_QNAME, features);
    }

    public CalculatorServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSERVICEIMPSERVICE_QNAME);
    }

    public CalculatorServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSERVICEIMPSERVICE_QNAME, features);
    }

    public CalculatorServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImpPort")
    public CalculatorService getCalculatorServiceImpPort() {
        return super.getPort(new QName("http://soap.service.labTA.com/", "CalculatorServiceImpPort"), CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImpPort")
    public CalculatorService getCalculatorServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.labTA.com/", "CalculatorServiceImpPort"), CalculatorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw CALCULATORSERVICEIMPSERVICE_EXCEPTION;
        }
        return CALCULATORSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
