
package com.epam.labTA.web.soap;

import com.epam.labTA.web.exception.ResponseError;
import io.restassured.response.Response;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://soap.service.labTA.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     * @throws SoapException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPercentage", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetPercentage")
    @ResponseWrapper(localName = "getPercentageResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetPercentageResponse")
    public Response getPercentage(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
            throws SoapException, ResponseError
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     * @throws SoapException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultiply", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetMultiply")
    @ResponseWrapper(localName = "getMultiplyResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetMultiplyResponse")
    public Response getMultiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
            throws SoapException, ResponseError
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @param arg2
     * @return
     *     returns double
     * @throws SoapException
     * @throws ResponseError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalculate", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetCalculate")
    @ResponseWrapper(localName = "getCalculateResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetCalculateResponse")
    public Response getCalculate(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
                String arg2)

        throws SoapException, ResponseError
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     * @throws SoapException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDivide", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetDivide")
    @ResponseWrapper(localName = "getDivideResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetDivideResponse")
    public Response getDivide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
            throws SoapException, ResponseError
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     * @throws SoapException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubtract", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetSubtract")
    @ResponseWrapper(localName = "getSubtractResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetSubtractResponse")
    public Response getSubtract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
            throws SoapException, ResponseError
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     * @throws SoapException
     *
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdd", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetAdd")
    @ResponseWrapper(localName = "getAddResponse", targetNamespace = "http://soap.service.labTA.com/", className = "com.labta.service.soap.GetAddResponse")
    public Response getAdd(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws SoapException, ResponseError;

}
